---
baseURL: "/"
languageCode:  "zh-Hans"
title: "Bigbig Zheng's Blog"
theme: "AllinOne"
description: "生命不息 奋斗不止！"



algolia:
  index: "myhugo"
  key: "90ab26ce13f03bb741dbf5503952f53d"
  appID: "0Q3QVS8ZFA"
---
